// Code generated by "stringer -type ConstKind"; DO NOT EDIT

package gc

import "fmt"

const _ConstKind_name = "BoolConstComplexConstFloatingPointConstIntConstRuneConstStringConst"

var _ConstKind_index = [...]uint8{0, 9, 21, 39, 47, 56, 67}

func (i ConstKind) String() string {
	i -= 1
	if i < 0 || i >= ConstKind(len(_ConstKind_index)-1) {
		return fmt.Sprintf("ConstKind(%d)", i+1)
	}
	return _ConstKind_name[_ConstKind_index[i]:_ConstKind_index[i+1]]
}
